# Generated by Django 3.2.7 on 2022-07-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questions_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
