# Generated by Django 3.2.7 on 2022-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0004_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=30, null=True)),
                ('option2', models.CharField(max_length=30, null=True)),
                ('option3', models.CharField(max_length=30, null=True)),
                ('option4', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
