# Generated by Django 3.2.7 on 2022-07-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('useraname', models.CharField(max_length=200)),
                ('points', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
