# Generated by Django 3.2.7 on 2022-07-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='useraname',
            new_name='username',
        ),
    ]
